import type { CardType } from "$lib/types";

export const cards: CardType[][] = [
  [
    {
      backgroundUrl: "/backgrounds/1.jpg",
      name: "Event One",
      description: "This is the first event.",
      date: "2023-10-01",
      time: "10:00 AM",
      location: "Location One",
      QRCode: "https://example.com/qrcode1.png",
    },
    {
      backgroundUrl: "/backgrounds/2.jpg",
      name: "Event Two",
      description: "This is the second event.",
      date: "2023-10-02",
      time: "11:00 AM",
      location: "Location Two",
      QRCode: "https://example.com/qrcode2.png",
    },
    {
      backgroundUrl: "/backgrounds/3.jpg",
      name: "Event Three",
      description: "This is the third event.",
      date: "2023-10-03",
      time: "12:00 PM",
      location: "Location Three",
      QRCode: "https://example.com/qrcode3.png",
    },
    {
      backgroundUrl: "/backgrounds/4.jpg",
      name: "Event Four",
      description: "This is the fourth event.",
      date: "2023-10-04",
      time: "01:00 PM",
      location: "Location Four",
      QRCode: "https://example.com/qrcode4.png",
    },
  ],
  [
    {
      backgroundUrl: "/backgrounds/5.jpg",
      name: "Event Five",
      description: "This is the fifth event.",
      date: "2023-10-05",
      time: "02:00 PM",
      location: "Location Five",
      QRCode: "https://example.com/qrcode5.png",
    },
    {
      backgroundUrl: "/backgrounds/6.jpg",
      name: "Event Six",
      description: "This is the sixth event.",
      date: "2023-10-06",
      time: "03:00 PM",
      location: "Location Six",
      QRCode: "https://example.com/qrcode6.png",
    },
    {
      backgroundUrl: "/backgrounds/7.jpg",
      name: "Event Seven",
      description: "This is the seventh event.",
      date: "2023-10-07",
      time: "04:00 PM",
      location: "Location Seven",
      QRCode: "https://example.com/qrcode7.png",
    },
    {
      backgroundUrl: "/backgrounds/8.jpg",
      name: "Event Eight",
      description: "This is the eighth event.",
      date: "2023-10-08",
      time: "05:00 PM",
      location: "Location Eight",
      QRCode: "https://example.com/qrcode8.png",
    },
  ],
  [
    {
      backgroundUrl: "/backgrounds/9.jpg",
      name: "Event Nine",
      description: "This is the ninth event.",
      date: "2023-10-09",
      time: "06:00 PM",
      location: "Location Nine",
      QRCode: "https://example.com/qrcode9.png",
    },
    {
      backgroundUrl: "/backgrounds/10.jpg",
      name: "Event Ten",
      description: "This is the tenth event.",
      date: "2023-10-10",
      time: "07:00 PM",
      location: "Location Ten",
      QRCode: "https://example.com/qrcode10.png",
    },
    {
      backgroundUrl: "/backgrounds/11.jpg",
      name: "Event Eleven",
      description: "This is the eleventh event.",
      date: "2023-10-11",
      time: "08:00 PM",
      location: "Location Eleven",
      QRCode: "https://example.com/qrcode11.png",
    },
    {
      backgroundUrl: "/backgrounds/12.jpg",
      name: "Event Twelve",
      description: "This is the twelfth event.",
      date: "2023-10-12",
      time: "09:00 PM",
      location: "Location Twelve",
      QRCode: "https://example.com/qrcode12.png",
    },
  ],
  [
    {
      backgroundUrl: "/backgrounds/13.jpg",
      name: "Event Thirteen",
      description: "This is the thirteenth event.",
      date: "2023-10-13",
      time: "10:00 AM",
      location: "Location Thirteen",
      QRCode: "https://example.com/qrcode13.png",
    },
    {
      backgroundUrl: "/backgrounds/14.jpg",
      name: "Event Fourteen",
      description: "This is the fourteenth event.",
      date: "2023-10-14",
      time: "11:00 AM",
      location: "Location Fourteen",
      QRCode: "https://example.com/qrcode14.png",
    },
    {
      backgroundUrl: "/backgrounds/15.jpg",
      name: "Event Fifteen",
      description: "This is the fifteenth event.",
      date: "2023-10-15",
      time: "12:00 PM",
      location: "Location Fifteen",
      QRCode: "https://example.com/qrcode15.png",
    },
    {
      backgroundUrl: "/backgrounds/16.jpg",
      name: "Event Sixteen",
      description: "This is the sixteenth event.",
      date: "2023-10-16",
      time: "01:00 PM",
      location: "Location Sixteen",
      QRCode: "https://example.com/qrcode16.png",
    },
  ],
];
